/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OffrePrix } from "./OffrePrix";
import { OffrePrixCountArgs } from "./OffrePrixCountArgs";
import { OffrePrixFindManyArgs } from "./OffrePrixFindManyArgs";
import { OffrePrixFindUniqueArgs } from "./OffrePrixFindUniqueArgs";
import { DeleteOffrePrixArgs } from "./DeleteOffrePrixArgs";
import { OffrePrixService } from "../offrePrix.service";
@graphql.Resolver(() => OffrePrix)
export class OffrePrixResolverBase {
  constructor(protected readonly service: OffrePrixService) {}

  async _offrePrixesMeta(
    @graphql.Args() args: OffrePrixCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OffrePrix])
  async offrePrixes(
    @graphql.Args() args: OffrePrixFindManyArgs
  ): Promise<OffrePrix[]> {
    return this.service.offrePrixes(args);
  }

  @graphql.Query(() => OffrePrix, { nullable: true })
  async offrePrix(
    @graphql.Args() args: OffrePrixFindUniqueArgs
  ): Promise<OffrePrix | null> {
    const result = await this.service.offrePrix(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OffrePrix)
  async deleteOffrePrix(
    @graphql.Args() args: DeleteOffrePrixArgs
  ): Promise<OffrePrix | null> {
    try {
      return await this.service.deleteOffrePrix(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
