/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "../../validators";
import {
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { CategorieProduitWhereUniqueInput } from "../../categorieProduit/base/CategorieProduitWhereUniqueInput";
import { Type } from "class-transformer";
import { ConditionnementProduitWhereUniqueInput } from "../../conditionnementProduit/base/ConditionnementProduitWhereUniqueInput";

@InputType()
class ProduitCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  caracteristiques?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => CategorieProduitWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategorieProduitWhereUniqueInput)
  @IsOptional()
  @Field(() => CategorieProduitWhereUniqueInput, {
    nullable: true,
  })
  categorieProduit?: CategorieProduitWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ConditionnementProduitWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ConditionnementProduitWhereUniqueInput)
  @IsOptional()
  @Field(() => ConditionnementProduitWhereUniqueInput, {
    nullable: true,
  })
  conditionnementProduit?: ConditionnementProduitWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  image?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nomenclature?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  referenceErp?: string | null;
}

export { ProduitCreateInput as ProduitCreateInput };
